name: kegs2023
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.*
  - numpy==1.23.5
  - xarray==2023.1.0
  - pandas==1.5.3
  - boule==0.4.1
  - ensaio==0.5.0
  - harmonica==0.5.1
  - verde==1.7.0
  - pyproj==3.4.1
  - pygmt==0.8.0
